name: Auto Commit

on:
  workflow_dispatch:

permissions:
  contents: write   # important pour autoriser le push

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make change
        run: echo "Update: $(date)" >> daily.log

      - name: Commit
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Auto commit" || echo "No changes"

      - name: Push
        run: git push
